-- users queries

-- Create managers table
CREATE TABLE managers (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create admins table
CREATE TABLE admins (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create users table
CREATE TABLE users (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    image VARCHAR(255),
    admin_id BIGINT UNSIGNED NOT NULL,
    password VARCHAR(255) NOT NULL,
    FOREIGN KEY (admin_id) REFERENCES admins(id) ON DELETE CASCADE,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create roles table
CREATE TABLE roles (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create admin_roles table
CREATE TABLE admin_roles (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    admin_id BIGINT UNSIGNED NOT NULL,
    role_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(255) NOT NULL,
    FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create user_roles table
CREATE TABLE user_roles (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    role_id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create permissions table
CREATE TABLE permissions (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create role_permissions table
CREATE TABLE role_permissions (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    role_id BIGINT UNSIGNED NOT NULL,
    permission_id BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
    FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- auctions queries

CREATE TABLE auctions (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    assignment_number VARCHAR(255) NOT NULL,
    auction_type ENUM('type1', 'type2', 'type3') NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    name VARCHAR(255) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id),
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE realestate_types (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE areas (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE cities (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    area_id BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (area_id) REFERENCES areas(id),
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE realestate_licenses (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    number INTEGER NOT NULL,
    issuance_place_id BIGINT UNSIGNED NOT NULL,
    realestate_type_id BIGINT UNSIGNED NOT NULL,
    date DATE NOT NULL,
    path VARCHAR(255) NOT NULL,
    note TEXT,
    FOREIGN KEY (issuance_place_id) REFERENCES cities(id),
    FOREIGN KEY (realestate_type_id) REFERENCES realestate_types(id),
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE quarters (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    city_id BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (city_id) REFERENCES cities(id),
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE realestate_documents (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    number VARCHAR(255) NOT NULL,
    area_number VARCHAR(255) NOT NULL,
    block_number VARCHAR(255) NOT NULL,
    graph_number VARCHAR(255) NOT NULL,
    space VARCHAR(255) NOT NULL,
    quarter_id BIGINT UNSIGNED NOT NULL,
    north_desc VARCHAR(255) NOT NULL,
    north_space INT NOT NULL,
    west_desc VARCHAR(255) NOT NULL,
    west_space INT NOT NULL,
    east_desc VARCHAR(255) NOT NULL,
    east_space INT NOT NULL,
    south_desc VARCHAR(255) NOT NULL,
    south_space INT NOT NULL,
    note TEXT,
    path VARCHAR(255),
    date TIMESTAMP NOT NULL,
    FOREIGN KEY (quarter_id) REFERENCES quarters(id),
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE realestates (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    customer_name VARCHAR(255) NOT NULL,
    owner_name VARCHAR(255) NOT NULL,
    owner_number VARCHAR(255) NOT NULL,
    customer_number VARCHAR(255) NOT NULL,
    auction_id BIGINT UNSIGNED NOT NULL,
    is_evaluated BOOLEAN DEFAULT false,
    license_id BIGINT UNSIGNED NOT NULL,
    document_id BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (auction_id) REFERENCES auctions(id),
    FOREIGN KEY (license_id) REFERENCES realestate_licenses(id),
    FOREIGN KEY (document_id) REFERENCES realestate_documents(id),
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE realestate_owners (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    identity_number INTEGER NOT NULL,
    nationality VARCHAR(255) NOT NULL,
    ownership_percentage INTEGER NOT NULL,
    realestate_id BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (realestate_id) REFERENCES realestates(id),
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE realestate_files (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    path VARCHAR(255) NOT NULL,
    realestate_id BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (realestate_id) REFERENCES realestates(id) ON DELETE CASCADE,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- scans queries

CREATE TABLE scans (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    lat VARCHAR(255) NOT NULL,
    lng VARCHAR(255) NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    realestate_id BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (realestate_id) REFERENCES realestates(id) ON DELETE CASCADE,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE properties (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type ENUM('text', 'single', 'multiple') NOT NULL,
    user_id BIGINT UNSIGNED,
    is_feature BOOLEAN DEFAULT 0,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE realestate_properties (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    realestate_id BIGINT UNSIGNED NOT NULL,
    property_id BIGINT UNSIGNED NOT NULL,
    properties_option_id BIGINT UNSIGNED,
    value VARCHAR(255),
    FOREIGN KEY (realestate_id) REFERENCES realestates(id) ON DELETE CASCADE,
    FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE,
    FOREIGN KEY (properties_option_id) REFERENCES properties_options(id) ON DELETE CASCADE,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE properties_options (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    property_id BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (property_id) REFERENCES properties(id) ON DELETE CASCADE,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE components (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    user_id BIGINT UNSIGNED,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE realestate_components (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    realestate_id BIGINT UNSIGNED NOT NULL,
    component_id BIGINT UNSIGNED NOT NULL,
    value VARCHAR(255) NOT NULL,
    FOREIGN KEY (realestate_id) REFERENCES realestates(id) ON DELETE CASCADE,
    FOREIGN KEY (component_id) REFERENCES components(id) ON DELETE CASCADE,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE orders (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    admin_id BIGINT UNSIGNED NOT NULL,
    auction_id BIGINT UNSIGNED NOT NULL,
    status ENUM('pending', 'completed', 'cancelled') NOT NULL,
    FOREIGN KEY (admin_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (auction_id) REFERENCES auctions(id) ON DELETE CASCADE,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE realestate_images_descriptions (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    description TEXT NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE realestate_images (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    path VARCHAR(255) NOT NULL,
    realestate_id BIGINT UNSIGNED,
    realestate_images_description_id BIGINT UNSIGNED,
    FOREIGN KEY (realestate_id) REFERENCES realestates(id) ON DELETE CASCADE,
    FOREIGN KEY (realestate_images_description_id) REFERENCES realestate_images_descriptions(id) ON DELETE CASCADE,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE realestate_features (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE realestate_feature_options (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    realestate_id BIGINT UNSIGNED NOT NULL,
    realestate_feature_id BIGINT UNSIGNED NOT NULL,
    value BOOLEAN NOT NULL,
    FOREIGN KEY (realestate_id) REFERENCES realestates(id) ON DELETE CASCADE,
    FOREIGN KEY (realestate_feature_id) REFERENCES realestate_features(id) ON DELETE CASCADE,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- evaluations queries

CREATE TABLE comparisons_evaluations (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    meter_price DECIMAL(65, 2),
    total_price DECIMAL(65, 2),
    realestate_id BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (realestate_id) REFERENCES realestates(id) ON DELETE CASCADE,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE direct_capitalization_evaluations (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    cross_income DECIMAL(10, 2) NOT NULL,
    operation_income_rate INT NOT NULL,
    capitalization_rate INT NOT NULL,
    realestate_total_value DECIMAL(10, 2) NOT NULL,
    net_income DECIMAL(10, 2) NOT NULL,
    operation_cost DECIMAL(10, 2) NOT NULL,
    realestate_id BIGINT UNSIGNED NOT NULL,
    FOREIGN KEY (realestate_id) REFERENCES realestates(id) ON DELETE CASCADE,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE comparisons_evaluation_properties (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );

CREATE TABLE comparisons_evaluation_realestates ( 
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
    comparisons_evaluation_id BIGINT UNSIGNED NOT NULL,
    meter_price DECIMAL(65, 2), 
    weighted INT, 
    FOREIGN KEY (comparisons_evaluation_id) REFERENCES comparisons_evaluations(id) ON DELETE CASCADE, 
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE comparisons_evaluation_realestates_properties (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    comparisons_evaluation_properties_id BIGINT UNSIGNED NOT NULL,
    comparisons_evaluation_realestate_id BIGINT UNSIGNED NOT NULL,
    percentage BIGINT NOT NULL,
    value VARCHAR(255) NOT NULL,
    FOREIGN KEY (comparisons_evaluation_properties_id) REFERENCES comparisons_evaluation_properties(id) ON DELETE CASCADE,
    FOREIGN KEY (comparisons_evaluation_realestate_id) REFERENCES comparisons_evaluation_realestates(id) ON DELETE CASCADE,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE cost_evaluations (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    realestate_id BIGINT UNSIGNED NOT NULL,
    total_cost DECIMAL(10, 2) NOT NULL,
    building_cost DECIMAL(10, 2) NOT NULL,
    building_cost_after_depreciation DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (realestate_id) REFERENCES realestates(id) ON DELETE CASCADE,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE direct_costs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    cost_evaluation_id BIGINT UNSIGNED NOT NULL,
    direct_cost DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (cost_evaluation_id) REFERENCES cost_evaluations(id) ON DELETE CASCADE,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
); 

CREATE TABLE direct_cost_components (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    direct_cost_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(255) NOT NULL,
    area INT NOT NULL,
    meter_price DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (direct_cost_id) REFERENCES direct_costs(id) ON DELETE CASCADE,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE indirect_costs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    cost_evaluation_id BIGINT UNSIGNED NOT NULL,
    indirect_cost DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (cost_evaluation_id) REFERENCES cost_evaluations(id) ON DELETE CASCADE,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE indirect_cost_components (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    indirect_cost_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(255) NOT NULL,
    percentage INT,
    price DECIMAL(10, 2),
    FOREIGN KEY (indirect_cost_id) REFERENCES indirect_costs(id) ON DELETE CASCADE,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE depreciations (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    cost_evaluation_id BIGINT UNSIGNED NOT NULL,
    realestate_life_span INT NOT NULL,
    realestate_expected_life_span INT NOT NULL,
    type ENUM('const', 'expanded') NOT NULL,
    depreciation_rate INT NOT NULL,
    depreciation_value DECIMAL(10, 2) NOT NULL,
    realestate_expanded_life_span INT,
    FOREIGN KEY (cost_evaluation_id) REFERENCES cost_evaluations(id) ON DELETE CASCADE,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);